const newPerson = document.querySelector("#luckyPerson");
// newPerson.innerHTML ="?"
newPerson.classList="text-4xl text-white"
const classMates = ['ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichaelD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Micheal A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichaelD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Micheal A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichaelD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Micheal A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',
'ZachF','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'ZachS',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad','Garrett', 'Nok', 'Britta', 'Easton','Emily', 'Zach',"Cindy", 'Claire', 'Ian', 'Jack','BrianL', 'BrianH', 'JenLiu', 'Ben', 'Keely' , 'Anthony', 'Lance' ,'Angelo', 'Mason', 'Alex', 'Maui', 'Michael A', 'Yohan', 'MichealD' ,'Victor', 'Yusuf', 'Thomas', 'JenL' ,'Lennon' , 'Steven','Peter' , 'Saad',




]

let list = document.querySelector("#listOfNames");
list.classList.add("flex", "flex-wrap","w-full")
const parent = document.querySelector("deleteDiv")

const randomizer = setInterval(randomPerson, 100);
const header = document.querySelector('#header')
const button = document.querySelector('#stop-button');
button.addEventListener('click', () => {
header.removeChild(button)
    newPerson.classList.add('text-9xl', 'text-black')
    clearInterval(randomizer);
});


function randomPerson(){

if (list.childNodes[0] !== undefined) {
    console.log("something")
    deleteDiv.removeChild(list);
    list = document.createElement('div');
    list.classList.add("flex", "flex-wrap","w-full")
    list.setAttribute("id", "listOfNames");
    deleteDiv.appendChild(list);
}

 const todaysVictim = classMates[Math.floor(Math.random() * classMates.length)];

 classMates.forEach(el=>{
    const currName = document.createElement('div');
    if(todaysVictim === el) {
        currName.innerText = el;
        currName.classList.add('mr-4', 'text-2xl','line-through','text-red-400')
        list.appendChild(currName)
    }else{
        currName.innerText = el;
        currName.classList.add('mr-4', 'text-2xl','text-black')
        list.appendChild(currName)
    }


 })

 newPerson.innerHTML = todaysVictim


}

const cover = document.querySelector("#cover")
const container = document.querySelector('#container')
function removeCover(){
container.removeChild(cover)

    // cover.classList.toggle("opacity-[92%]")
    // cover.classList.add('opacity-0')
}